%##########################################################################
% Stress-induced mutation rate spikes.
%
% Hypothesis: Lag time arises from the time difference between stress
% exposure and cellular mutagenic response.
%
% Initial condition: Mostly normal cells with a small population of
% mutators.
% Normal cells have a low growth rate and a low death rate. Upon stress,
% there is a spike in the mutation rate, causing some cells to shift
% transiently into the mutator class (subpopulation 2).
% Mutators have a low growth rate (same as normal cells) and a high 
% mutation rate. Most mutants generated by the mutators are deleterious, 
% while a few are beneficial. In the model, this is represented by a high 
% death rate in the mutator subpopulation and a low "hitchhiking" rate, 
% at which beneficial mutators survive and mutators hitchhike on them.
%
% The mutator alleles hitchhike on beneficial mutations, which replicate 
% clonally. These hitchhiker cells make up the third subpopulation.
% Hitchhiker cells have a high growth rate AND a high death rate because
% they contain mutators. They also have a high (constant) escape rate.
% Cells which escape become part of the fourth subpopulation, the escaped
% cells. These cells have a high growth rate and do not mutate.
%
%##########################################################################

% TODO
% --> transient vs genetic mutator?
% --> fitness modifier for hitchhiker/escape cells

function dxdt = population_odes(t, x)
    %########## PARAMETERS ##########    
    g_eng = 0.01; g_esc = 0.36;
    d_wt = 0.0004; d_mut = 0.1; % h^-1
    eng2mut = @(t) 0.5 * spike(t) + spike(t - 20);
    mut2hit = @(t) 5e-4 * one(t);
    hit2esc = @(t) 5e-2 * one(t);
    

    % g_eng = .102; d_eng = .1;
    % g_mut = .105; d_mut = .1;
    % m = @(t) 0.5 * spike(t) + spike(t - 20);
    % % m = @(t) const(t);

    P_max = 10000; % TODO: vary this with time (P_eff)
    %################################

    eng = x(1); % engineered cells
    mut = x(2); % mutators
    hit = x(3); % hitchhikers
    esc = x(4); % escaped cells

    logistic = 1 - (eng+mut+hit+esc) / P_max;

    dengdt = ((g_eng - d_wt) * eng - eng2mut(t) * eng) * logistic;
    dmutdt = ((g_eng - d_mut) * mut + eng2mut(t) * eng - mut2hit(t) * mut) * logistic;
    dhitdt = ((g_esc - d_mut) * hit + mut2hit(t) * mut - hit2esc(t) * hit) * logistic;
    descdt = ((g_esc - d_wt) * esc + hit2esc(t) * hit) * logistic;

    dxdt = [dengdt; dmutdt; dhitdt; descdt];
end

function y = spike(t) 
    %########## PARAMETERS ##########
    % r_min; r_max;
    % t0; tf;
    r_min = 5e-5; r_max = 5e-3;
    t0 = 10; tf = 15;
    %################################

    slope = (r_max - r_min) / (0.5 * (tf - t0));

    if (t < t0)
        y = r_min;
    elseif (t < (tf + t0)/2)
        y = slope * (t - t0) + r_min;
    elseif (t < tf)
        y = -1 * slope * (t - (tf + t0)/2) + r_max;
    else
        y = r_min;
    end
end

function y = one(t)
    y = 1;
end

%########## INITIAL CONDITIONS ##########
eng0 = 1200; mut0 = 20; hit0 = 0; esc0 = 0;
%########################################

[t,y] = ode45(@population_odes,[0 200],[eng0; mut0; hit0; esc0]);

figure;
subplot(3,1,1); plot(t, y, LineWidth=2);
title("Subpopulation size vs. time"); legend("Engineered", "Mutator", "Hitchhiker", "Escaped");

subplot(3,1,2); plot(t, sum(y, 2), LineWidth=2);
title("Total population size vs. time");

subplot(3,1,3); fplot(@(t) 0.5 * spike(t) + spike(t - 20), [0 200])
title("Mutation rate vs time");

