%##########################################################################
% Stress-induced mutation rate spikes.
%
% Hypothesis: Lag time arises from the time difference between stress
% exposure and cellular mutagenic response.
%
% Initial condition: Mostly normal cells with a small population of
% mutators.
%
% SUBPOPULATION 1: NORMAL CELLS
    % Normal cells have a low growth rate and a low death rate. Upon stress,
    % there is a spike in the mutation rate, causing some cells to shift
    % transiently into the mutator class (subpopulation 2).
% SUBPOPULATION 2: MUTATORS
    % Mutators have a low growth rate (same as normal cells) and a high 
    % mutation rate. Most mutants generated by the mutators are deleterious, 
    % while a few are beneficial. In the model, this is represented by a high 
    % death rate in the mutator subpopulation and a low "hitchhiking" rate, 
    % at which beneficial mutators survive and mutators hitchhike on them.
% SUBPOPULATION 3: HITCHHIKERS
    % The mutator alleles hitchhike on beneficial mutations, which replicate 
    % clonally. These hitchhiker cells make up the third subpopulation.
    % Hitchhiker cells have a high growth rate AND a high death rate because
    % they contain mutators. They also have a high (constant) escape rate.
% SUBPOPULATION 4: CHEATERS/ESCAPERS
    % Cells which escape become part of the fourth subpopulation, the escaped
    % cells. These cells have a high growth rate and do not mutate.
%
%##########################################################################

% TODO
% --> transient vs genetic mutator?
% --> fitness modifier (logistic term) for hitchhiker/escape cells

global light_exp_times light_exp_lengths;
light_exp_times = [10, 30, 70];
light_exp_lengths = [5, 10, 15];

function dxdt = population_odes(t, x)
    %########## PARAMETERS ##########    
    g_eng = 0.01; g_esc = 0.36; g_wt = 0.5;
    d_wt = 0.0004; d_mut = 0.1; % h^-1
    eng2mut = @(t) e2m(t);    
    mut2hit = @(t) 5e-4 * one(t);
    hit2esc = @(t) 5e-2 * one(t);

    P_total = 10000;
    P_eng_noLight = 1300;
    P_eng_light = P_total;
    P_mut = 3000;
    P_hit = 8000;
    P_esc = 8000;
    space_const = 0.5;
    %################################

    eng = x(1); % engineered cells
    mut = x(2); % mutators
    hit = x(3); % hitchhikers
    esc = x(4); % escaped cells

    % logistic = 1 - (eng+mut+hit+esc) / P_total;

    dengdt = ((g_eng - d_wt) * eng - eng2mut(t) * eng) * (1 - eng/P_eng_noLight) * (1 - light(t)) ... % dynamics in growth restriction
           + ((g_wt - d_wt) * eng - eng2mut(t) * eng) * (1 - eng/P_eng_light) * light(t);  % dynamics in growth permission
    dmutdt = ((g_eng - d_mut) * mut + eng2mut(t) * eng - mut2hit(t) * mut) * (1 - mut/P_mut);
    dhitdt = ((g_esc - d_mut) * hit + mut2hit(t) * mut - hit2esc(t) * hit) * (1 - hit/P_hit);
    descdt = ((g_esc - d_wt) * esc + hit2esc(t) * hit) * (1 - esc/P_esc);

    dxdt = [dengdt; dmutdt; dhitdt; descdt];
end

function y = light(t)
    %########## PARAMETERS ##########
    % light_exp_times = [10, 30, 70];
    % light_exp_lengths = [5, 10, 15];
    global light_exp_times light_exp_lengths;
    %################################

    y = 0;
    for i = 1:length(light_exp_times)
        y = y + heaviside(t - light_exp_times(i)) ...
            - heaviside(t- (light_exp_times(i) + light_exp_lengths(i)));
    end
end

function y = e2m(t)
    %########## PARAMETERS ##########
    delay = 3;
    spike_length = 10;
    global light_exp_times light_exp_lengths;
    %################################ 
    
    spike_times = light_exp_times + light_exp_lengths + delay;
    
    y = 0;
    for i = 1:length(spike_times)
        y = y + spike(t-spike_times(i), spike_length);
    end

    % y = spike(t - 20, 20) + spike(t-75, 20);
    % y = 0.5 * spike(t, 10) + spike(t - 20, 20);
end

function y = spike(t, length)
    %########## PARAMETERS ##########
    r_min = 5e-5; 
    r_max = 5e-3;
    t0 = 0; 
    tf = t0 + length;
    %################################

    slope = (r_max - r_min) / (0.5 * (tf - t0));
    tm = (tf + t0) / 2;

    y = r_min * ones(size(t));

    rise = (t >= t0) & (t < tm);
    fall = (t >= tm) & (t < tf);

    y(rise) = slope * (t(rise) - t0) + r_min;
    y(fall) = -slope * (t(fall) - tm) + r_max;
end

function y = one(t)
    y = 1;
end

%########## INITIAL CONDITIONS ##########
eng0 = 1200; mut0 = 0; hit0 = 0; esc0 = 0;
%########################################

[t,y] = ode45(@population_odes,[0 200],[eng0; mut0; hit0; esc0]);
colors = lines(4);

figure;
subplot(3,1,1); 
yyaxis left; plot(t, sum(y, 2), LineWidth=2);
xregion(light_exp_times, light_exp_times+light_exp_lengths, FaceColor=[100/255, 225/255, 240/255], FaceAlpha=0.2);
title("Total population size vs. time");

subplot(3,1,2); 
yyaxis left; plot(t, y, LineWidth=2); colororder(colors);
xregion(light_exp_times, light_exp_times+light_exp_lengths, FaceColor=[100/255, 225/255, 240/255], FaceAlpha=0.2);
title("Subpopulation size vs. time"); legend("Engineered", "Mutator", "Hitchhiker", "Escaped");

subplot(3,1,3);
yyaxis left; fplot(@(t) e2m(t), [0 200], LineWidth=2, LineStyle='--', Color='r');
xregion(light_exp_times, light_exp_times+light_exp_lengths, FaceColor=[100/255, 225/255, 240/255], FaceAlpha=0.2);
title("Light exposure and rate of mutator formation vs time (e2m(t))");

figure;
titles = ["Engineered", "Mutator", "Hitchhiker", "Cheater"];
for i=1:4
    subplot(2,2,i);
    yyaxis left; plot(t, y(:,i), LineWidth=2);
    yyaxis right; hold on; fplot(@(t) e2m(t), [0 200], LineStyle="--");
    xregion(light_exp_times, light_exp_times+light_exp_lengths, FaceColor=[100/255, 225/255, 240/255], FaceAlpha=0.2);
    title(titles(i))
end